---
- name: Add Google NTP servers
  blockinfile:
    dest: '/etc/chrony.conf'
    state: present
    content: |
      # Google NTP servers
      server time1.google.com iburst
      server time2.google.com iburst
      server time3.google.com iburst
      server time4.google.com iburst
