---
- hosts: all
  gather_facts: false
  connection: local
  user: remote
  sudo: true

  tasks:
    - vsphere_guest:
        validate_certs: false
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ inventory_hostname }}"
        state: "{{ state }}"
        vm_extra_config:
          folder: "{{ folder }}"
          notes: "{{ notes }}"
        vm_disk:
          disk1:
            size_gb: "{{ disk }}"
            type: thin
            datastore: "{{ datastore }}"
        vm_nic:
          nic1:
            type: vmxnet3
            network: "{{ network }}"
            network_type: "{{ network_type }}"
        vm_hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          osid: "{{ osid }}"
          scsi: lsi
          vm_cdrom:
            type: "iso"
            iso_path: "{{ iso_image }}"
        esxi:
          datacenter: "{{ datacenter }}"
          hostname: "{{ esxi_host }}"
