---
- name: Install rpm packages
  yum: name={{ item }} state=latest
  with_items:
    - chrony
    - git
    - libselinux-python
    - lsof
    - nmap
    - open-vm-tools
    - tcpdump
    - tree
    - unzip
    - wget
    - yum-utils
