---
- name: Disable default NTP
  replace:
    dest: '/etc/chrony/chrony.conf'
    regexp: '^pool 2.debian.pool.ntp.org offline iburst'
    replace: '#pool 2.debian.pool.ntp.org offline iburst'
- name: Add Google NTP servers
  blockinfile:
    dest: '/etc/chrony/chrony.conf'
    state: present
    content: |
      # Google NTP servers
      server time1.google.com iburst
      server time2.google.com iburst
      server time3.google.com iburst
      server time4.google.com iburst
- name: Restart chrony
  service: name=chrony enabled=yes state=restarted
  ignore_errors: True
