---
- name: Disable NTP (0.centos.pool.ntp.org)
  replace:
    dest: '/etc/chrony.conf'
    regexp: '^server 0.centos.pool.ntp.org iburst'
    replace: '#server 0.centos.pool.ntp.org iburst'
- name: Disable NTP (1.centos.pool.ntp.org)
  replace:
    dest: '/etc/chrony.conf'
    regexp: '^server 1.centos.pool.ntp.org iburst'
    replace: '#server 1.centos.pool.ntp.org iburst'
- name: Disable NTP (2.centos.pool.ntp.org)
  replace:
    dest: '/etc/chrony.conf'
    regexp: '^server 2.centos.pool.ntp.org iburst'
    replace: '#server 2.centos.pool.ntp.org iburst'
- name: Disable NTP (3.centos.pool.ntp.org)
  replace:
    dest: '/etc/chrony.conf'
    regexp: '^server 3.centos.pool.ntp.org iburst'
    replace: '#server 3.centos.pool.ntp.org iburst'

